package com.uom.cse.central_node.services;


import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-12-28")
public class myChangeInformation implements org.apache.thrift.TBase<myChangeInformation, myChangeInformation._Fields>, java.io.Serializable, Cloneable, Comparable<myChangeInformation> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("myChangeInformation");

  private static final org.apache.thrift.protocol.TField CHANGE__TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("Change_Type", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new myChangeInformationStandardSchemeFactory());
    schemes.put(TupleScheme.class, new myChangeInformationTupleSchemeFactory());
  }

  public String Change_Type; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CHANGE__TYPE((short)1, "Change_Type");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CHANGE__TYPE
          return CHANGE__TYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CHANGE__TYPE, new org.apache.thrift.meta_data.FieldMetaData("Change_Type", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(myChangeInformation.class, metaDataMap);
  }

  public myChangeInformation() {
  }

  public myChangeInformation(
    String Change_Type)
  {
    this();
    this.Change_Type = Change_Type;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public myChangeInformation(myChangeInformation other) {
    if (other.isSetChange_Type()) {
      this.Change_Type = other.Change_Type;
    }
  }

  public myChangeInformation deepCopy() {
    return new myChangeInformation(this);
  }

  @Override
  public void clear() {
    this.Change_Type = null;
  }

  public String getChange_Type() {
    return this.Change_Type;
  }

  public myChangeInformation setChange_Type(String Change_Type) {
    this.Change_Type = Change_Type;
    return this;
  }

  public void unsetChange_Type() {
    this.Change_Type = null;
  }

  /** Returns true if field Change_Type is set (has been assigned a value) and false otherwise */
  public boolean isSetChange_Type() {
    return this.Change_Type != null;
  }

  public void setChange_TypeIsSet(boolean value) {
    if (!value) {
      this.Change_Type = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CHANGE__TYPE:
      if (value == null) {
        unsetChange_Type();
      } else {
        setChange_Type((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CHANGE__TYPE:
      return getChange_Type();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CHANGE__TYPE:
      return isSetChange_Type();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof myChangeInformation)
      return this.equals((myChangeInformation)that);
    return false;
  }

  public boolean equals(myChangeInformation that) {
    if (that == null)
      return false;

    boolean this_present_Change_Type = true && this.isSetChange_Type();
    boolean that_present_Change_Type = true && that.isSetChange_Type();
    if (this_present_Change_Type || that_present_Change_Type) {
      if (!(this_present_Change_Type && that_present_Change_Type))
        return false;
      if (!this.Change_Type.equals(that.Change_Type))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_Change_Type = true && (isSetChange_Type());
    list.add(present_Change_Type);
    if (present_Change_Type)
      list.add(Change_Type);

    return list.hashCode();
  }

  @Override
  public int compareTo(myChangeInformation other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetChange_Type()).compareTo(other.isSetChange_Type());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetChange_Type()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Change_Type, other.Change_Type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("myChangeInformation(");
    boolean first = true;

    sb.append("Change_Type:");
    if (this.Change_Type == null) {
      sb.append("null");
    } else {
      sb.append(this.Change_Type);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class myChangeInformationStandardSchemeFactory implements SchemeFactory {
    public myChangeInformationStandardScheme getScheme() {
      return new myChangeInformationStandardScheme();
    }
  }

  private static class myChangeInformationStandardScheme extends StandardScheme<myChangeInformation> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, myChangeInformation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CHANGE__TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.Change_Type = iprot.readString();
              struct.setChange_TypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, myChangeInformation struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.Change_Type != null) {
        oprot.writeFieldBegin(CHANGE__TYPE_FIELD_DESC);
        oprot.writeString(struct.Change_Type);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class myChangeInformationTupleSchemeFactory implements SchemeFactory {
    public myChangeInformationTupleScheme getScheme() {
      return new myChangeInformationTupleScheme();
    }
  }

  private static class myChangeInformationTupleScheme extends TupleScheme<myChangeInformation> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, myChangeInformation struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetChange_Type()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetChange_Type()) {
        oprot.writeString(struct.Change_Type);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, myChangeInformation struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.Change_Type = iprot.readString();
        struct.setChange_TypeIsSet(true);
      }
    }
  }

}

