/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.uom.cse.central_node.services;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-1-13")
public class myLayerInformation implements org.apache.thrift.TBase<myLayerInformation, myLayerInformation._Fields>, java.io.Serializable, Cloneable, Comparable<myLayerInformation> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("myLayerInformation");

  private static final org.apache.thrift.protocol.TField LAYER__ID_FIELD_DESC = new org.apache.thrift.protocol.TField("Layer_ID", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField LAYER__NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("Layer_Name", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField LAYER__RUNTIME__ID_FIELD_DESC = new org.apache.thrift.protocol.TField("Layer_Runtime_ID", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new myLayerInformationStandardSchemeFactory());
    schemes.put(TupleScheme.class, new myLayerInformationTupleSchemeFactory());
  }

  public String Layer_ID; // required
  public String Layer_Name; // required
  public String Layer_Runtime_ID; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LAYER__ID((short)1, "Layer_ID"),
    LAYER__NAME((short)2, "Layer_Name"),
    LAYER__RUNTIME__ID((short)3, "Layer_Runtime_ID");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LAYER__ID
          return LAYER__ID;
        case 2: // LAYER__NAME
          return LAYER__NAME;
        case 3: // LAYER__RUNTIME__ID
          return LAYER__RUNTIME__ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LAYER__ID, new org.apache.thrift.meta_data.FieldMetaData("Layer_ID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LAYER__NAME, new org.apache.thrift.meta_data.FieldMetaData("Layer_Name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LAYER__RUNTIME__ID, new org.apache.thrift.meta_data.FieldMetaData("Layer_Runtime_ID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(myLayerInformation.class, metaDataMap);
  }

  public myLayerInformation() {
  }

  public myLayerInformation(
    String Layer_ID,
    String Layer_Name,
    String Layer_Runtime_ID)
  {
    this();
    this.Layer_ID = Layer_ID;
    this.Layer_Name = Layer_Name;
    this.Layer_Runtime_ID = Layer_Runtime_ID;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public myLayerInformation(myLayerInformation other) {
    if (other.isSetLayer_ID()) {
      this.Layer_ID = other.Layer_ID;
    }
    if (other.isSetLayer_Name()) {
      this.Layer_Name = other.Layer_Name;
    }
    if (other.isSetLayer_Runtime_ID()) {
      this.Layer_Runtime_ID = other.Layer_Runtime_ID;
    }
  }

  public myLayerInformation deepCopy() {
    return new myLayerInformation(this);
  }

  @Override
  public void clear() {
    this.Layer_ID = null;
    this.Layer_Name = null;
    this.Layer_Runtime_ID = null;
  }

  public String getLayer_ID() {
    return this.Layer_ID;
  }

  public myLayerInformation setLayer_ID(String Layer_ID) {
    this.Layer_ID = Layer_ID;
    return this;
  }

  public void unsetLayer_ID() {
    this.Layer_ID = null;
  }

  /** Returns true if field Layer_ID is set (has been assigned a value) and false otherwise */
  public boolean isSetLayer_ID() {
    return this.Layer_ID != null;
  }

  public void setLayer_IDIsSet(boolean value) {
    if (!value) {
      this.Layer_ID = null;
    }
  }

  public String getLayer_Name() {
    return this.Layer_Name;
  }

  public myLayerInformation setLayer_Name(String Layer_Name) {
    this.Layer_Name = Layer_Name;
    return this;
  }

  public void unsetLayer_Name() {
    this.Layer_Name = null;
  }

  /** Returns true if field Layer_Name is set (has been assigned a value) and false otherwise */
  public boolean isSetLayer_Name() {
    return this.Layer_Name != null;
  }

  public void setLayer_NameIsSet(boolean value) {
    if (!value) {
      this.Layer_Name = null;
    }
  }

  public String getLayer_Runtime_ID() {
    return this.Layer_Runtime_ID;
  }

  public myLayerInformation setLayer_Runtime_ID(String Layer_Runtime_ID) {
    this.Layer_Runtime_ID = Layer_Runtime_ID;
    return this;
  }

  public void unsetLayer_Runtime_ID() {
    this.Layer_Runtime_ID = null;
  }

  /** Returns true if field Layer_Runtime_ID is set (has been assigned a value) and false otherwise */
  public boolean isSetLayer_Runtime_ID() {
    return this.Layer_Runtime_ID != null;
  }

  public void setLayer_Runtime_IDIsSet(boolean value) {
    if (!value) {
      this.Layer_Runtime_ID = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case LAYER__ID:
      if (value == null) {
        unsetLayer_ID();
      } else {
        setLayer_ID((String)value);
      }
      break;

    case LAYER__NAME:
      if (value == null) {
        unsetLayer_Name();
      } else {
        setLayer_Name((String)value);
      }
      break;

    case LAYER__RUNTIME__ID:
      if (value == null) {
        unsetLayer_Runtime_ID();
      } else {
        setLayer_Runtime_ID((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case LAYER__ID:
      return getLayer_ID();

    case LAYER__NAME:
      return getLayer_Name();

    case LAYER__RUNTIME__ID:
      return getLayer_Runtime_ID();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case LAYER__ID:
      return isSetLayer_ID();
    case LAYER__NAME:
      return isSetLayer_Name();
    case LAYER__RUNTIME__ID:
      return isSetLayer_Runtime_ID();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof myLayerInformation)
      return this.equals((myLayerInformation)that);
    return false;
  }

  public boolean equals(myLayerInformation that) {
    if (that == null)
      return false;

    boolean this_present_Layer_ID = true && this.isSetLayer_ID();
    boolean that_present_Layer_ID = true && that.isSetLayer_ID();
    if (this_present_Layer_ID || that_present_Layer_ID) {
      if (!(this_present_Layer_ID && that_present_Layer_ID))
        return false;
      if (!this.Layer_ID.equals(that.Layer_ID))
        return false;
    }

    boolean this_present_Layer_Name = true && this.isSetLayer_Name();
    boolean that_present_Layer_Name = true && that.isSetLayer_Name();
    if (this_present_Layer_Name || that_present_Layer_Name) {
      if (!(this_present_Layer_Name && that_present_Layer_Name))
        return false;
      if (!this.Layer_Name.equals(that.Layer_Name))
        return false;
    }

    boolean this_present_Layer_Runtime_ID = true && this.isSetLayer_Runtime_ID();
    boolean that_present_Layer_Runtime_ID = true && that.isSetLayer_Runtime_ID();
    if (this_present_Layer_Runtime_ID || that_present_Layer_Runtime_ID) {
      if (!(this_present_Layer_Runtime_ID && that_present_Layer_Runtime_ID))
        return false;
      if (!this.Layer_Runtime_ID.equals(that.Layer_Runtime_ID))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_Layer_ID = true && (isSetLayer_ID());
    list.add(present_Layer_ID);
    if (present_Layer_ID)
      list.add(Layer_ID);

    boolean present_Layer_Name = true && (isSetLayer_Name());
    list.add(present_Layer_Name);
    if (present_Layer_Name)
      list.add(Layer_Name);

    boolean present_Layer_Runtime_ID = true && (isSetLayer_Runtime_ID());
    list.add(present_Layer_Runtime_ID);
    if (present_Layer_Runtime_ID)
      list.add(Layer_Runtime_ID);

    return list.hashCode();
  }

  @Override
  public int compareTo(myLayerInformation other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetLayer_ID()).compareTo(other.isSetLayer_ID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLayer_ID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Layer_ID, other.Layer_ID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLayer_Name()).compareTo(other.isSetLayer_Name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLayer_Name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Layer_Name, other.Layer_Name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLayer_Runtime_ID()).compareTo(other.isSetLayer_Runtime_ID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLayer_Runtime_ID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Layer_Runtime_ID, other.Layer_Runtime_ID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("myLayerInformation(");
    boolean first = true;

    sb.append("Layer_ID:");
    if (this.Layer_ID == null) {
      sb.append("null");
    } else {
      sb.append(this.Layer_ID);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("Layer_Name:");
    if (this.Layer_Name == null) {
      sb.append("null");
    } else {
      sb.append(this.Layer_Name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("Layer_Runtime_ID:");
    if (this.Layer_Runtime_ID == null) {
      sb.append("null");
    } else {
      sb.append(this.Layer_Runtime_ID);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class myLayerInformationStandardSchemeFactory implements SchemeFactory {
    public myLayerInformationStandardScheme getScheme() {
      return new myLayerInformationStandardScheme();
    }
  }

  private static class myLayerInformationStandardScheme extends StandardScheme<myLayerInformation> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, myLayerInformation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LAYER__ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.Layer_ID = iprot.readString();
              struct.setLayer_IDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // LAYER__NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.Layer_Name = iprot.readString();
              struct.setLayer_NameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // LAYER__RUNTIME__ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.Layer_Runtime_ID = iprot.readString();
              struct.setLayer_Runtime_IDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, myLayerInformation struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.Layer_ID != null) {
        oprot.writeFieldBegin(LAYER__ID_FIELD_DESC);
        oprot.writeString(struct.Layer_ID);
        oprot.writeFieldEnd();
      }
      if (struct.Layer_Name != null) {
        oprot.writeFieldBegin(LAYER__NAME_FIELD_DESC);
        oprot.writeString(struct.Layer_Name);
        oprot.writeFieldEnd();
      }
      if (struct.Layer_Runtime_ID != null) {
        oprot.writeFieldBegin(LAYER__RUNTIME__ID_FIELD_DESC);
        oprot.writeString(struct.Layer_Runtime_ID);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class myLayerInformationTupleSchemeFactory implements SchemeFactory {
    public myLayerInformationTupleScheme getScheme() {
      return new myLayerInformationTupleScheme();
    }
  }

  private static class myLayerInformationTupleScheme extends TupleScheme<myLayerInformation> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, myLayerInformation struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetLayer_ID()) {
        optionals.set(0);
      }
      if (struct.isSetLayer_Name()) {
        optionals.set(1);
      }
      if (struct.isSetLayer_Runtime_ID()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetLayer_ID()) {
        oprot.writeString(struct.Layer_ID);
      }
      if (struct.isSetLayer_Name()) {
        oprot.writeString(struct.Layer_Name);
      }
      if (struct.isSetLayer_Runtime_ID()) {
        oprot.writeString(struct.Layer_Runtime_ID);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, myLayerInformation struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.Layer_ID = iprot.readString();
        struct.setLayer_IDIsSet(true);
      }
      if (incoming.get(1)) {
        struct.Layer_Name = iprot.readString();
        struct.setLayer_NameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.Layer_Runtime_ID = iprot.readString();
        struct.setLayer_Runtime_IDIsSet(true);
      }
    }
  }

}

