package com.uom.cse.central_node.services;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-12-30")
public class myProcessInformation implements org.apache.thrift.TBase<myProcessInformation, myProcessInformation._Fields>, java.io.Serializable, Cloneable, Comparable<myProcessInformation> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("myProcessInformation");

  private static final org.apache.thrift.protocol.TField PROCESS__ID_FIELD_DESC = new org.apache.thrift.protocol.TField("Process_ID", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PROCESS__NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("Process_Name", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new myProcessInformationStandardSchemeFactory());
    schemes.put(TupleScheme.class, new myProcessInformationTupleSchemeFactory());
  }

  public String Process_ID; // required
  public String Process_Name; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PROCESS__ID((short)1, "Process_ID"),
    PROCESS__NAME((short)2, "Process_Name");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PROCESS__ID
          return PROCESS__ID;
        case 2: // PROCESS__NAME
          return PROCESS__NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PROCESS__ID, new org.apache.thrift.meta_data.FieldMetaData("Process_ID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PROCESS__NAME, new org.apache.thrift.meta_data.FieldMetaData("Process_Name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(myProcessInformation.class, metaDataMap);
  }

  public myProcessInformation() {
  }

  public myProcessInformation(
    String Process_ID,
    String Process_Name)
  {
    this();
    this.Process_ID = Process_ID;
    this.Process_Name = Process_Name;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public myProcessInformation(myProcessInformation other) {
    if (other.isSetProcess_ID()) {
      this.Process_ID = other.Process_ID;
    }
    if (other.isSetProcess_Name()) {
      this.Process_Name = other.Process_Name;
    }
  }

  public myProcessInformation deepCopy() {
    return new myProcessInformation(this);
  }

  @Override
  public void clear() {
    this.Process_ID = null;
    this.Process_Name = null;
  }

  public String getProcess_ID() {
    return this.Process_ID;
  }

  public myProcessInformation setProcess_ID(String Process_ID) {
    this.Process_ID = Process_ID;
    return this;
  }

  public void unsetProcess_ID() {
    this.Process_ID = null;
  }

  /** Returns true if field Process_ID is set (has been assigned a value) and false otherwise */
  public boolean isSetProcess_ID() {
    return this.Process_ID != null;
  }

  public void setProcess_IDIsSet(boolean value) {
    if (!value) {
      this.Process_ID = null;
    }
  }

  public String getProcess_Name() {
    return this.Process_Name;
  }

  public myProcessInformation setProcess_Name(String Process_Name) {
    this.Process_Name = Process_Name;
    return this;
  }

  public void unsetProcess_Name() {
    this.Process_Name = null;
  }

  /** Returns true if field Process_Name is set (has been assigned a value) and false otherwise */
  public boolean isSetProcess_Name() {
    return this.Process_Name != null;
  }

  public void setProcess_NameIsSet(boolean value) {
    if (!value) {
      this.Process_Name = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PROCESS__ID:
      if (value == null) {
        unsetProcess_ID();
      } else {
        setProcess_ID((String)value);
      }
      break;

    case PROCESS__NAME:
      if (value == null) {
        unsetProcess_Name();
      } else {
        setProcess_Name((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PROCESS__ID:
      return getProcess_ID();

    case PROCESS__NAME:
      return getProcess_Name();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PROCESS__ID:
      return isSetProcess_ID();
    case PROCESS__NAME:
      return isSetProcess_Name();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof myProcessInformation)
      return this.equals((myProcessInformation)that);
    return false;
  }

  public boolean equals(myProcessInformation that) {
    if (that == null)
      return false;

    boolean this_present_Process_ID = true && this.isSetProcess_ID();
    boolean that_present_Process_ID = true && that.isSetProcess_ID();
    if (this_present_Process_ID || that_present_Process_ID) {
      if (!(this_present_Process_ID && that_present_Process_ID))
        return false;
      if (!this.Process_ID.equals(that.Process_ID))
        return false;
    }

    boolean this_present_Process_Name = true && this.isSetProcess_Name();
    boolean that_present_Process_Name = true && that.isSetProcess_Name();
    if (this_present_Process_Name || that_present_Process_Name) {
      if (!(this_present_Process_Name && that_present_Process_Name))
        return false;
      if (!this.Process_Name.equals(that.Process_Name))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_Process_ID = true && (isSetProcess_ID());
    list.add(present_Process_ID);
    if (present_Process_ID)
      list.add(Process_ID);

    boolean present_Process_Name = true && (isSetProcess_Name());
    list.add(present_Process_Name);
    if (present_Process_Name)
      list.add(Process_Name);

    return list.hashCode();
  }

  @Override
  public int compareTo(myProcessInformation other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetProcess_ID()).compareTo(other.isSetProcess_ID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProcess_ID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Process_ID, other.Process_ID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProcess_Name()).compareTo(other.isSetProcess_Name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProcess_Name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Process_Name, other.Process_Name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("myProcessInformation(");
    boolean first = true;

    sb.append("Process_ID:");
    if (this.Process_ID == null) {
      sb.append("null");
    } else {
      sb.append(this.Process_ID);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("Process_Name:");
    if (this.Process_Name == null) {
      sb.append("null");
    } else {
      sb.append(this.Process_Name);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class myProcessInformationStandardSchemeFactory implements SchemeFactory {
    public myProcessInformationStandardScheme getScheme() {
      return new myProcessInformationStandardScheme();
    }
  }

  private static class myProcessInformationStandardScheme extends StandardScheme<myProcessInformation> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, myProcessInformation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PROCESS__ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.Process_ID = iprot.readString();
              struct.setProcess_IDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PROCESS__NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.Process_Name = iprot.readString();
              struct.setProcess_NameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, myProcessInformation struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.Process_ID != null) {
        oprot.writeFieldBegin(PROCESS__ID_FIELD_DESC);
        oprot.writeString(struct.Process_ID);
        oprot.writeFieldEnd();
      }
      if (struct.Process_Name != null) {
        oprot.writeFieldBegin(PROCESS__NAME_FIELD_DESC);
        oprot.writeString(struct.Process_Name);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class myProcessInformationTupleSchemeFactory implements SchemeFactory {
    public myProcessInformationTupleScheme getScheme() {
      return new myProcessInformationTupleScheme();
    }
  }

  private static class myProcessInformationTupleScheme extends TupleScheme<myProcessInformation> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, myProcessInformation struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetProcess_ID()) {
        optionals.set(0);
      }
      if (struct.isSetProcess_Name()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetProcess_ID()) {
        oprot.writeString(struct.Process_ID);
      }
      if (struct.isSetProcess_Name()) {
        oprot.writeString(struct.Process_Name);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, myProcessInformation struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.Process_ID = iprot.readString();
        struct.setProcess_IDIsSet(true);
      }
      if (incoming.get(1)) {
        struct.Process_Name = iprot.readString();
        struct.setProcess_NameIsSet(true);
      }
    }
  }

}

