/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.uom.cse.central_node.services;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2016-1-13")
public class myUserAccountDetailsStruct implements org.apache.thrift.TBase<myUserAccountDetailsStruct, myUserAccountDetailsStruct._Fields>, java.io.Serializable, Cloneable, Comparable<myUserAccountDetailsStruct> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("myUserAccountDetailsStruct");

  private static final org.apache.thrift.protocol.TField COMPUTER_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("computerName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField USRI4_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_name", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField USRI4_PASSWORD_AGE_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_password_age", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField USRI4_PRIV_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_priv", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField USRI4_FLAGS_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_flags", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField USRI4_USR_COMMENT_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_usr_comment", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField USRI4_PARMS_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_parms", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField USRI4_LAST_LOGON_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_last_logon", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField USRI4_LAST_LOGOFF_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_last_logoff", org.apache.thrift.protocol.TType.STRING, (short)9);
  private static final org.apache.thrift.protocol.TField USRI4_ACCT_EXPIRES_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_acct_expires", org.apache.thrift.protocol.TType.STRING, (short)10);
  private static final org.apache.thrift.protocol.TField USRI4_MAX_STORAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_max_storage", org.apache.thrift.protocol.TType.STRING, (short)11);
  private static final org.apache.thrift.protocol.TField USRI4_UNITS_PER_WEEK_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_units_per_week", org.apache.thrift.protocol.TType.STRING, (short)12);
  private static final org.apache.thrift.protocol.TField USRI4_LOGON_HOURS_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_logon_hours", org.apache.thrift.protocol.TType.STRING, (short)13);
  private static final org.apache.thrift.protocol.TField USRI4_BAD_PW_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_bad_pw_count", org.apache.thrift.protocol.TType.STRING, (short)14);
  private static final org.apache.thrift.protocol.TField USRI4_NUM_LOGONS_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_num_logons", org.apache.thrift.protocol.TType.STRING, (short)15);
  private static final org.apache.thrift.protocol.TField USRI4_COUNTRY_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_country_code", org.apache.thrift.protocol.TType.STRING, (short)16);
  private static final org.apache.thrift.protocol.TField USRI4_CODE_PAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_code_page", org.apache.thrift.protocol.TType.STRING, (short)17);
  private static final org.apache.thrift.protocol.TField USRI4_PRIMARY_GROUP_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_primary_group_id", org.apache.thrift.protocol.TType.STRING, (short)18);
  private static final org.apache.thrift.protocol.TField USRI4_PROFILE_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_profile", org.apache.thrift.protocol.TType.STRING, (short)19);
  private static final org.apache.thrift.protocol.TField USRI4_PASSWORD_EXPIRED_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_password_expired", org.apache.thrift.protocol.TType.STRING, (short)20);
  private static final org.apache.thrift.protocol.TField USRI4_AUTH_FLAGS_FIELD_DESC = new org.apache.thrift.protocol.TField("usri4_auth_flags", org.apache.thrift.protocol.TType.STRING, (short)21);
  private static final org.apache.thrift.protocol.TField MAC_FIELD_DESC = new org.apache.thrift.protocol.TField("mac", org.apache.thrift.protocol.TType.STRING, (short)22);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new myUserAccountDetailsStructStandardSchemeFactory());
    schemes.put(TupleScheme.class, new myUserAccountDetailsStructTupleSchemeFactory());
  }

  public String computerName; // required
  public String usri4_name; // required
  public String usri4_password_age; // required
  public String usri4_priv; // required
  public String usri4_flags; // required
  public String usri4_usr_comment; // required
  public String usri4_parms; // required
  public String usri4_last_logon; // required
  public String usri4_last_logoff; // required
  public String usri4_acct_expires; // required
  public String usri4_max_storage; // required
  public String usri4_units_per_week; // required
  public String usri4_logon_hours; // required
  public String usri4_bad_pw_count; // required
  public String usri4_num_logons; // required
  public String usri4_country_code; // required
  public String usri4_code_page; // required
  public String usri4_primary_group_id; // required
  public String usri4_profile; // required
  public String usri4_password_expired; // required
  public String usri4_auth_flags; // required
  public String mac; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    COMPUTER_NAME((short)1, "computerName"),
    USRI4_NAME((short)2, "usri4_name"),
    USRI4_PASSWORD_AGE((short)3, "usri4_password_age"),
    USRI4_PRIV((short)4, "usri4_priv"),
    USRI4_FLAGS((short)5, "usri4_flags"),
    USRI4_USR_COMMENT((short)6, "usri4_usr_comment"),
    USRI4_PARMS((short)7, "usri4_parms"),
    USRI4_LAST_LOGON((short)8, "usri4_last_logon"),
    USRI4_LAST_LOGOFF((short)9, "usri4_last_logoff"),
    USRI4_ACCT_EXPIRES((short)10, "usri4_acct_expires"),
    USRI4_MAX_STORAGE((short)11, "usri4_max_storage"),
    USRI4_UNITS_PER_WEEK((short)12, "usri4_units_per_week"),
    USRI4_LOGON_HOURS((short)13, "usri4_logon_hours"),
    USRI4_BAD_PW_COUNT((short)14, "usri4_bad_pw_count"),
    USRI4_NUM_LOGONS((short)15, "usri4_num_logons"),
    USRI4_COUNTRY_CODE((short)16, "usri4_country_code"),
    USRI4_CODE_PAGE((short)17, "usri4_code_page"),
    USRI4_PRIMARY_GROUP_ID((short)18, "usri4_primary_group_id"),
    USRI4_PROFILE((short)19, "usri4_profile"),
    USRI4_PASSWORD_EXPIRED((short)20, "usri4_password_expired"),
    USRI4_AUTH_FLAGS((short)21, "usri4_auth_flags"),
    MAC((short)22, "mac");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // COMPUTER_NAME
          return COMPUTER_NAME;
        case 2: // USRI4_NAME
          return USRI4_NAME;
        case 3: // USRI4_PASSWORD_AGE
          return USRI4_PASSWORD_AGE;
        case 4: // USRI4_PRIV
          return USRI4_PRIV;
        case 5: // USRI4_FLAGS
          return USRI4_FLAGS;
        case 6: // USRI4_USR_COMMENT
          return USRI4_USR_COMMENT;
        case 7: // USRI4_PARMS
          return USRI4_PARMS;
        case 8: // USRI4_LAST_LOGON
          return USRI4_LAST_LOGON;
        case 9: // USRI4_LAST_LOGOFF
          return USRI4_LAST_LOGOFF;
        case 10: // USRI4_ACCT_EXPIRES
          return USRI4_ACCT_EXPIRES;
        case 11: // USRI4_MAX_STORAGE
          return USRI4_MAX_STORAGE;
        case 12: // USRI4_UNITS_PER_WEEK
          return USRI4_UNITS_PER_WEEK;
        case 13: // USRI4_LOGON_HOURS
          return USRI4_LOGON_HOURS;
        case 14: // USRI4_BAD_PW_COUNT
          return USRI4_BAD_PW_COUNT;
        case 15: // USRI4_NUM_LOGONS
          return USRI4_NUM_LOGONS;
        case 16: // USRI4_COUNTRY_CODE
          return USRI4_COUNTRY_CODE;
        case 17: // USRI4_CODE_PAGE
          return USRI4_CODE_PAGE;
        case 18: // USRI4_PRIMARY_GROUP_ID
          return USRI4_PRIMARY_GROUP_ID;
        case 19: // USRI4_PROFILE
          return USRI4_PROFILE;
        case 20: // USRI4_PASSWORD_EXPIRED
          return USRI4_PASSWORD_EXPIRED;
        case 21: // USRI4_AUTH_FLAGS
          return USRI4_AUTH_FLAGS;
        case 22: // MAC
          return MAC;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.COMPUTER_NAME, new org.apache.thrift.meta_data.FieldMetaData("computerName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_NAME, new org.apache.thrift.meta_data.FieldMetaData("usri4_name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_PASSWORD_AGE, new org.apache.thrift.meta_data.FieldMetaData("usri4_password_age", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_PRIV, new org.apache.thrift.meta_data.FieldMetaData("usri4_priv", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_FLAGS, new org.apache.thrift.meta_data.FieldMetaData("usri4_flags", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_USR_COMMENT, new org.apache.thrift.meta_data.FieldMetaData("usri4_usr_comment", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_PARMS, new org.apache.thrift.meta_data.FieldMetaData("usri4_parms", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_LAST_LOGON, new org.apache.thrift.meta_data.FieldMetaData("usri4_last_logon", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_LAST_LOGOFF, new org.apache.thrift.meta_data.FieldMetaData("usri4_last_logoff", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_ACCT_EXPIRES, new org.apache.thrift.meta_data.FieldMetaData("usri4_acct_expires", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_MAX_STORAGE, new org.apache.thrift.meta_data.FieldMetaData("usri4_max_storage", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_UNITS_PER_WEEK, new org.apache.thrift.meta_data.FieldMetaData("usri4_units_per_week", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_LOGON_HOURS, new org.apache.thrift.meta_data.FieldMetaData("usri4_logon_hours", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_BAD_PW_COUNT, new org.apache.thrift.meta_data.FieldMetaData("usri4_bad_pw_count", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_NUM_LOGONS, new org.apache.thrift.meta_data.FieldMetaData("usri4_num_logons", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_COUNTRY_CODE, new org.apache.thrift.meta_data.FieldMetaData("usri4_country_code", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_CODE_PAGE, new org.apache.thrift.meta_data.FieldMetaData("usri4_code_page", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_PRIMARY_GROUP_ID, new org.apache.thrift.meta_data.FieldMetaData("usri4_primary_group_id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_PROFILE, new org.apache.thrift.meta_data.FieldMetaData("usri4_profile", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_PASSWORD_EXPIRED, new org.apache.thrift.meta_data.FieldMetaData("usri4_password_expired", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.USRI4_AUTH_FLAGS, new org.apache.thrift.meta_data.FieldMetaData("usri4_auth_flags", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.MAC, new org.apache.thrift.meta_data.FieldMetaData("mac", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(myUserAccountDetailsStruct.class, metaDataMap);
  }

  public myUserAccountDetailsStruct() {
  }

  public myUserAccountDetailsStruct(
    String computerName,
    String usri4_name,
    String usri4_password_age,
    String usri4_priv,
    String usri4_flags,
    String usri4_usr_comment,
    String usri4_parms,
    String usri4_last_logon,
    String usri4_last_logoff,
    String usri4_acct_expires,
    String usri4_max_storage,
    String usri4_units_per_week,
    String usri4_logon_hours,
    String usri4_bad_pw_count,
    String usri4_num_logons,
    String usri4_country_code,
    String usri4_code_page,
    String usri4_primary_group_id,
    String usri4_profile,
    String usri4_password_expired,
    String usri4_auth_flags,
    String mac)
  {
    this();
    this.computerName = computerName;
    this.usri4_name = usri4_name;
    this.usri4_password_age = usri4_password_age;
    this.usri4_priv = usri4_priv;
    this.usri4_flags = usri4_flags;
    this.usri4_usr_comment = usri4_usr_comment;
    this.usri4_parms = usri4_parms;
    this.usri4_last_logon = usri4_last_logon;
    this.usri4_last_logoff = usri4_last_logoff;
    this.usri4_acct_expires = usri4_acct_expires;
    this.usri4_max_storage = usri4_max_storage;
    this.usri4_units_per_week = usri4_units_per_week;
    this.usri4_logon_hours = usri4_logon_hours;
    this.usri4_bad_pw_count = usri4_bad_pw_count;
    this.usri4_num_logons = usri4_num_logons;
    this.usri4_country_code = usri4_country_code;
    this.usri4_code_page = usri4_code_page;
    this.usri4_primary_group_id = usri4_primary_group_id;
    this.usri4_profile = usri4_profile;
    this.usri4_password_expired = usri4_password_expired;
    this.usri4_auth_flags = usri4_auth_flags;
    this.mac = mac;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public myUserAccountDetailsStruct(myUserAccountDetailsStruct other) {
    if (other.isSetComputerName()) {
      this.computerName = other.computerName;
    }
    if (other.isSetUsri4_name()) {
      this.usri4_name = other.usri4_name;
    }
    if (other.isSetUsri4_password_age()) {
      this.usri4_password_age = other.usri4_password_age;
    }
    if (other.isSetUsri4_priv()) {
      this.usri4_priv = other.usri4_priv;
    }
    if (other.isSetUsri4_flags()) {
      this.usri4_flags = other.usri4_flags;
    }
    if (other.isSetUsri4_usr_comment()) {
      this.usri4_usr_comment = other.usri4_usr_comment;
    }
    if (other.isSetUsri4_parms()) {
      this.usri4_parms = other.usri4_parms;
    }
    if (other.isSetUsri4_last_logon()) {
      this.usri4_last_logon = other.usri4_last_logon;
    }
    if (other.isSetUsri4_last_logoff()) {
      this.usri4_last_logoff = other.usri4_last_logoff;
    }
    if (other.isSetUsri4_acct_expires()) {
      this.usri4_acct_expires = other.usri4_acct_expires;
    }
    if (other.isSetUsri4_max_storage()) {
      this.usri4_max_storage = other.usri4_max_storage;
    }
    if (other.isSetUsri4_units_per_week()) {
      this.usri4_units_per_week = other.usri4_units_per_week;
    }
    if (other.isSetUsri4_logon_hours()) {
      this.usri4_logon_hours = other.usri4_logon_hours;
    }
    if (other.isSetUsri4_bad_pw_count()) {
      this.usri4_bad_pw_count = other.usri4_bad_pw_count;
    }
    if (other.isSetUsri4_num_logons()) {
      this.usri4_num_logons = other.usri4_num_logons;
    }
    if (other.isSetUsri4_country_code()) {
      this.usri4_country_code = other.usri4_country_code;
    }
    if (other.isSetUsri4_code_page()) {
      this.usri4_code_page = other.usri4_code_page;
    }
    if (other.isSetUsri4_primary_group_id()) {
      this.usri4_primary_group_id = other.usri4_primary_group_id;
    }
    if (other.isSetUsri4_profile()) {
      this.usri4_profile = other.usri4_profile;
    }
    if (other.isSetUsri4_password_expired()) {
      this.usri4_password_expired = other.usri4_password_expired;
    }
    if (other.isSetUsri4_auth_flags()) {
      this.usri4_auth_flags = other.usri4_auth_flags;
    }
    if (other.isSetMac()) {
      this.mac = other.mac;
    }
  }

  public myUserAccountDetailsStruct deepCopy() {
    return new myUserAccountDetailsStruct(this);
  }

  @Override
  public void clear() {
    this.computerName = null;
    this.usri4_name = null;
    this.usri4_password_age = null;
    this.usri4_priv = null;
    this.usri4_flags = null;
    this.usri4_usr_comment = null;
    this.usri4_parms = null;
    this.usri4_last_logon = null;
    this.usri4_last_logoff = null;
    this.usri4_acct_expires = null;
    this.usri4_max_storage = null;
    this.usri4_units_per_week = null;
    this.usri4_logon_hours = null;
    this.usri4_bad_pw_count = null;
    this.usri4_num_logons = null;
    this.usri4_country_code = null;
    this.usri4_code_page = null;
    this.usri4_primary_group_id = null;
    this.usri4_profile = null;
    this.usri4_password_expired = null;
    this.usri4_auth_flags = null;
    this.mac = null;
  }

  public String getComputerName() {
    return this.computerName;
  }

  public myUserAccountDetailsStruct setComputerName(String computerName) {
    this.computerName = computerName;
    return this;
  }

  public void unsetComputerName() {
    this.computerName = null;
  }

  /** Returns true if field computerName is set (has been assigned a value) and false otherwise */
  public boolean isSetComputerName() {
    return this.computerName != null;
  }

  public void setComputerNameIsSet(boolean value) {
    if (!value) {
      this.computerName = null;
    }
  }

  public String getUsri4_name() {
    return this.usri4_name;
  }

  public myUserAccountDetailsStruct setUsri4_name(String usri4_name) {
    this.usri4_name = usri4_name;
    return this;
  }

  public void unsetUsri4_name() {
    this.usri4_name = null;
  }

  /** Returns true if field usri4_name is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_name() {
    return this.usri4_name != null;
  }

  public void setUsri4_nameIsSet(boolean value) {
    if (!value) {
      this.usri4_name = null;
    }
  }

  public String getUsri4_password_age() {
    return this.usri4_password_age;
  }

  public myUserAccountDetailsStruct setUsri4_password_age(String usri4_password_age) {
    this.usri4_password_age = usri4_password_age;
    return this;
  }

  public void unsetUsri4_password_age() {
    this.usri4_password_age = null;
  }

  /** Returns true if field usri4_password_age is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_password_age() {
    return this.usri4_password_age != null;
  }

  public void setUsri4_password_ageIsSet(boolean value) {
    if (!value) {
      this.usri4_password_age = null;
    }
  }

  public String getUsri4_priv() {
    return this.usri4_priv;
  }

  public myUserAccountDetailsStruct setUsri4_priv(String usri4_priv) {
    this.usri4_priv = usri4_priv;
    return this;
  }

  public void unsetUsri4_priv() {
    this.usri4_priv = null;
  }

  /** Returns true if field usri4_priv is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_priv() {
    return this.usri4_priv != null;
  }

  public void setUsri4_privIsSet(boolean value) {
    if (!value) {
      this.usri4_priv = null;
    }
  }

  public String getUsri4_flags() {
    return this.usri4_flags;
  }

  public myUserAccountDetailsStruct setUsri4_flags(String usri4_flags) {
    this.usri4_flags = usri4_flags;
    return this;
  }

  public void unsetUsri4_flags() {
    this.usri4_flags = null;
  }

  /** Returns true if field usri4_flags is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_flags() {
    return this.usri4_flags != null;
  }

  public void setUsri4_flagsIsSet(boolean value) {
    if (!value) {
      this.usri4_flags = null;
    }
  }

  public String getUsri4_usr_comment() {
    return this.usri4_usr_comment;
  }

  public myUserAccountDetailsStruct setUsri4_usr_comment(String usri4_usr_comment) {
    this.usri4_usr_comment = usri4_usr_comment;
    return this;
  }

  public void unsetUsri4_usr_comment() {
    this.usri4_usr_comment = null;
  }

  /** Returns true if field usri4_usr_comment is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_usr_comment() {
    return this.usri4_usr_comment != null;
  }

  public void setUsri4_usr_commentIsSet(boolean value) {
    if (!value) {
      this.usri4_usr_comment = null;
    }
  }

  public String getUsri4_parms() {
    return this.usri4_parms;
  }

  public myUserAccountDetailsStruct setUsri4_parms(String usri4_parms) {
    this.usri4_parms = usri4_parms;
    return this;
  }

  public void unsetUsri4_parms() {
    this.usri4_parms = null;
  }

  /** Returns true if field usri4_parms is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_parms() {
    return this.usri4_parms != null;
  }

  public void setUsri4_parmsIsSet(boolean value) {
    if (!value) {
      this.usri4_parms = null;
    }
  }

  public String getUsri4_last_logon() {
    return this.usri4_last_logon;
  }

  public myUserAccountDetailsStruct setUsri4_last_logon(String usri4_last_logon) {
    this.usri4_last_logon = usri4_last_logon;
    return this;
  }

  public void unsetUsri4_last_logon() {
    this.usri4_last_logon = null;
  }

  /** Returns true if field usri4_last_logon is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_last_logon() {
    return this.usri4_last_logon != null;
  }

  public void setUsri4_last_logonIsSet(boolean value) {
    if (!value) {
      this.usri4_last_logon = null;
    }
  }

  public String getUsri4_last_logoff() {
    return this.usri4_last_logoff;
  }

  public myUserAccountDetailsStruct setUsri4_last_logoff(String usri4_last_logoff) {
    this.usri4_last_logoff = usri4_last_logoff;
    return this;
  }

  public void unsetUsri4_last_logoff() {
    this.usri4_last_logoff = null;
  }

  /** Returns true if field usri4_last_logoff is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_last_logoff() {
    return this.usri4_last_logoff != null;
  }

  public void setUsri4_last_logoffIsSet(boolean value) {
    if (!value) {
      this.usri4_last_logoff = null;
    }
  }

  public String getUsri4_acct_expires() {
    return this.usri4_acct_expires;
  }

  public myUserAccountDetailsStruct setUsri4_acct_expires(String usri4_acct_expires) {
    this.usri4_acct_expires = usri4_acct_expires;
    return this;
  }

  public void unsetUsri4_acct_expires() {
    this.usri4_acct_expires = null;
  }

  /** Returns true if field usri4_acct_expires is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_acct_expires() {
    return this.usri4_acct_expires != null;
  }

  public void setUsri4_acct_expiresIsSet(boolean value) {
    if (!value) {
      this.usri4_acct_expires = null;
    }
  }

  public String getUsri4_max_storage() {
    return this.usri4_max_storage;
  }

  public myUserAccountDetailsStruct setUsri4_max_storage(String usri4_max_storage) {
    this.usri4_max_storage = usri4_max_storage;
    return this;
  }

  public void unsetUsri4_max_storage() {
    this.usri4_max_storage = null;
  }

  /** Returns true if field usri4_max_storage is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_max_storage() {
    return this.usri4_max_storage != null;
  }

  public void setUsri4_max_storageIsSet(boolean value) {
    if (!value) {
      this.usri4_max_storage = null;
    }
  }

  public String getUsri4_units_per_week() {
    return this.usri4_units_per_week;
  }

  public myUserAccountDetailsStruct setUsri4_units_per_week(String usri4_units_per_week) {
    this.usri4_units_per_week = usri4_units_per_week;
    return this;
  }

  public void unsetUsri4_units_per_week() {
    this.usri4_units_per_week = null;
  }

  /** Returns true if field usri4_units_per_week is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_units_per_week() {
    return this.usri4_units_per_week != null;
  }

  public void setUsri4_units_per_weekIsSet(boolean value) {
    if (!value) {
      this.usri4_units_per_week = null;
    }
  }

  public String getUsri4_logon_hours() {
    return this.usri4_logon_hours;
  }

  public myUserAccountDetailsStruct setUsri4_logon_hours(String usri4_logon_hours) {
    this.usri4_logon_hours = usri4_logon_hours;
    return this;
  }

  public void unsetUsri4_logon_hours() {
    this.usri4_logon_hours = null;
  }

  /** Returns true if field usri4_logon_hours is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_logon_hours() {
    return this.usri4_logon_hours != null;
  }

  public void setUsri4_logon_hoursIsSet(boolean value) {
    if (!value) {
      this.usri4_logon_hours = null;
    }
  }

  public String getUsri4_bad_pw_count() {
    return this.usri4_bad_pw_count;
  }

  public myUserAccountDetailsStruct setUsri4_bad_pw_count(String usri4_bad_pw_count) {
    this.usri4_bad_pw_count = usri4_bad_pw_count;
    return this;
  }

  public void unsetUsri4_bad_pw_count() {
    this.usri4_bad_pw_count = null;
  }

  /** Returns true if field usri4_bad_pw_count is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_bad_pw_count() {
    return this.usri4_bad_pw_count != null;
  }

  public void setUsri4_bad_pw_countIsSet(boolean value) {
    if (!value) {
      this.usri4_bad_pw_count = null;
    }
  }

  public String getUsri4_num_logons() {
    return this.usri4_num_logons;
  }

  public myUserAccountDetailsStruct setUsri4_num_logons(String usri4_num_logons) {
    this.usri4_num_logons = usri4_num_logons;
    return this;
  }

  public void unsetUsri4_num_logons() {
    this.usri4_num_logons = null;
  }

  /** Returns true if field usri4_num_logons is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_num_logons() {
    return this.usri4_num_logons != null;
  }

  public void setUsri4_num_logonsIsSet(boolean value) {
    if (!value) {
      this.usri4_num_logons = null;
    }
  }

  public String getUsri4_country_code() {
    return this.usri4_country_code;
  }

  public myUserAccountDetailsStruct setUsri4_country_code(String usri4_country_code) {
    this.usri4_country_code = usri4_country_code;
    return this;
  }

  public void unsetUsri4_country_code() {
    this.usri4_country_code = null;
  }

  /** Returns true if field usri4_country_code is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_country_code() {
    return this.usri4_country_code != null;
  }

  public void setUsri4_country_codeIsSet(boolean value) {
    if (!value) {
      this.usri4_country_code = null;
    }
  }

  public String getUsri4_code_page() {
    return this.usri4_code_page;
  }

  public myUserAccountDetailsStruct setUsri4_code_page(String usri4_code_page) {
    this.usri4_code_page = usri4_code_page;
    return this;
  }

  public void unsetUsri4_code_page() {
    this.usri4_code_page = null;
  }

  /** Returns true if field usri4_code_page is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_code_page() {
    return this.usri4_code_page != null;
  }

  public void setUsri4_code_pageIsSet(boolean value) {
    if (!value) {
      this.usri4_code_page = null;
    }
  }

  public String getUsri4_primary_group_id() {
    return this.usri4_primary_group_id;
  }

  public myUserAccountDetailsStruct setUsri4_primary_group_id(String usri4_primary_group_id) {
    this.usri4_primary_group_id = usri4_primary_group_id;
    return this;
  }

  public void unsetUsri4_primary_group_id() {
    this.usri4_primary_group_id = null;
  }

  /** Returns true if field usri4_primary_group_id is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_primary_group_id() {
    return this.usri4_primary_group_id != null;
  }

  public void setUsri4_primary_group_idIsSet(boolean value) {
    if (!value) {
      this.usri4_primary_group_id = null;
    }
  }

  public String getUsri4_profile() {
    return this.usri4_profile;
  }

  public myUserAccountDetailsStruct setUsri4_profile(String usri4_profile) {
    this.usri4_profile = usri4_profile;
    return this;
  }

  public void unsetUsri4_profile() {
    this.usri4_profile = null;
  }

  /** Returns true if field usri4_profile is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_profile() {
    return this.usri4_profile != null;
  }

  public void setUsri4_profileIsSet(boolean value) {
    if (!value) {
      this.usri4_profile = null;
    }
  }

  public String getUsri4_password_expired() {
    return this.usri4_password_expired;
  }

  public myUserAccountDetailsStruct setUsri4_password_expired(String usri4_password_expired) {
    this.usri4_password_expired = usri4_password_expired;
    return this;
  }

  public void unsetUsri4_password_expired() {
    this.usri4_password_expired = null;
  }

  /** Returns true if field usri4_password_expired is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_password_expired() {
    return this.usri4_password_expired != null;
  }

  public void setUsri4_password_expiredIsSet(boolean value) {
    if (!value) {
      this.usri4_password_expired = null;
    }
  }

  public String getUsri4_auth_flags() {
    return this.usri4_auth_flags;
  }

  public myUserAccountDetailsStruct setUsri4_auth_flags(String usri4_auth_flags) {
    this.usri4_auth_flags = usri4_auth_flags;
    return this;
  }

  public void unsetUsri4_auth_flags() {
    this.usri4_auth_flags = null;
  }

  /** Returns true if field usri4_auth_flags is set (has been assigned a value) and false otherwise */
  public boolean isSetUsri4_auth_flags() {
    return this.usri4_auth_flags != null;
  }

  public void setUsri4_auth_flagsIsSet(boolean value) {
    if (!value) {
      this.usri4_auth_flags = null;
    }
  }

  public String getMac() {
    return this.mac;
  }

  public myUserAccountDetailsStruct setMac(String mac) {
    this.mac = mac;
    return this;
  }

  public void unsetMac() {
    this.mac = null;
  }

  /** Returns true if field mac is set (has been assigned a value) and false otherwise */
  public boolean isSetMac() {
    return this.mac != null;
  }

  public void setMacIsSet(boolean value) {
    if (!value) {
      this.mac = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case COMPUTER_NAME:
      if (value == null) {
        unsetComputerName();
      } else {
        setComputerName((String)value);
      }
      break;

    case USRI4_NAME:
      if (value == null) {
        unsetUsri4_name();
      } else {
        setUsri4_name((String)value);
      }
      break;

    case USRI4_PASSWORD_AGE:
      if (value == null) {
        unsetUsri4_password_age();
      } else {
        setUsri4_password_age((String)value);
      }
      break;

    case USRI4_PRIV:
      if (value == null) {
        unsetUsri4_priv();
      } else {
        setUsri4_priv((String)value);
      }
      break;

    case USRI4_FLAGS:
      if (value == null) {
        unsetUsri4_flags();
      } else {
        setUsri4_flags((String)value);
      }
      break;

    case USRI4_USR_COMMENT:
      if (value == null) {
        unsetUsri4_usr_comment();
      } else {
        setUsri4_usr_comment((String)value);
      }
      break;

    case USRI4_PARMS:
      if (value == null) {
        unsetUsri4_parms();
      } else {
        setUsri4_parms((String)value);
      }
      break;

    case USRI4_LAST_LOGON:
      if (value == null) {
        unsetUsri4_last_logon();
      } else {
        setUsri4_last_logon((String)value);
      }
      break;

    case USRI4_LAST_LOGOFF:
      if (value == null) {
        unsetUsri4_last_logoff();
      } else {
        setUsri4_last_logoff((String)value);
      }
      break;

    case USRI4_ACCT_EXPIRES:
      if (value == null) {
        unsetUsri4_acct_expires();
      } else {
        setUsri4_acct_expires((String)value);
      }
      break;

    case USRI4_MAX_STORAGE:
      if (value == null) {
        unsetUsri4_max_storage();
      } else {
        setUsri4_max_storage((String)value);
      }
      break;

    case USRI4_UNITS_PER_WEEK:
      if (value == null) {
        unsetUsri4_units_per_week();
      } else {
        setUsri4_units_per_week((String)value);
      }
      break;

    case USRI4_LOGON_HOURS:
      if (value == null) {
        unsetUsri4_logon_hours();
      } else {
        setUsri4_logon_hours((String)value);
      }
      break;

    case USRI4_BAD_PW_COUNT:
      if (value == null) {
        unsetUsri4_bad_pw_count();
      } else {
        setUsri4_bad_pw_count((String)value);
      }
      break;

    case USRI4_NUM_LOGONS:
      if (value == null) {
        unsetUsri4_num_logons();
      } else {
        setUsri4_num_logons((String)value);
      }
      break;

    case USRI4_COUNTRY_CODE:
      if (value == null) {
        unsetUsri4_country_code();
      } else {
        setUsri4_country_code((String)value);
      }
      break;

    case USRI4_CODE_PAGE:
      if (value == null) {
        unsetUsri4_code_page();
      } else {
        setUsri4_code_page((String)value);
      }
      break;

    case USRI4_PRIMARY_GROUP_ID:
      if (value == null) {
        unsetUsri4_primary_group_id();
      } else {
        setUsri4_primary_group_id((String)value);
      }
      break;

    case USRI4_PROFILE:
      if (value == null) {
        unsetUsri4_profile();
      } else {
        setUsri4_profile((String)value);
      }
      break;

    case USRI4_PASSWORD_EXPIRED:
      if (value == null) {
        unsetUsri4_password_expired();
      } else {
        setUsri4_password_expired((String)value);
      }
      break;

    case USRI4_AUTH_FLAGS:
      if (value == null) {
        unsetUsri4_auth_flags();
      } else {
        setUsri4_auth_flags((String)value);
      }
      break;

    case MAC:
      if (value == null) {
        unsetMac();
      } else {
        setMac((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case COMPUTER_NAME:
      return getComputerName();

    case USRI4_NAME:
      return getUsri4_name();

    case USRI4_PASSWORD_AGE:
      return getUsri4_password_age();

    case USRI4_PRIV:
      return getUsri4_priv();

    case USRI4_FLAGS:
      return getUsri4_flags();

    case USRI4_USR_COMMENT:
      return getUsri4_usr_comment();

    case USRI4_PARMS:
      return getUsri4_parms();

    case USRI4_LAST_LOGON:
      return getUsri4_last_logon();

    case USRI4_LAST_LOGOFF:
      return getUsri4_last_logoff();

    case USRI4_ACCT_EXPIRES:
      return getUsri4_acct_expires();

    case USRI4_MAX_STORAGE:
      return getUsri4_max_storage();

    case USRI4_UNITS_PER_WEEK:
      return getUsri4_units_per_week();

    case USRI4_LOGON_HOURS:
      return getUsri4_logon_hours();

    case USRI4_BAD_PW_COUNT:
      return getUsri4_bad_pw_count();

    case USRI4_NUM_LOGONS:
      return getUsri4_num_logons();

    case USRI4_COUNTRY_CODE:
      return getUsri4_country_code();

    case USRI4_CODE_PAGE:
      return getUsri4_code_page();

    case USRI4_PRIMARY_GROUP_ID:
      return getUsri4_primary_group_id();

    case USRI4_PROFILE:
      return getUsri4_profile();

    case USRI4_PASSWORD_EXPIRED:
      return getUsri4_password_expired();

    case USRI4_AUTH_FLAGS:
      return getUsri4_auth_flags();

    case MAC:
      return getMac();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case COMPUTER_NAME:
      return isSetComputerName();
    case USRI4_NAME:
      return isSetUsri4_name();
    case USRI4_PASSWORD_AGE:
      return isSetUsri4_password_age();
    case USRI4_PRIV:
      return isSetUsri4_priv();
    case USRI4_FLAGS:
      return isSetUsri4_flags();
    case USRI4_USR_COMMENT:
      return isSetUsri4_usr_comment();
    case USRI4_PARMS:
      return isSetUsri4_parms();
    case USRI4_LAST_LOGON:
      return isSetUsri4_last_logon();
    case USRI4_LAST_LOGOFF:
      return isSetUsri4_last_logoff();
    case USRI4_ACCT_EXPIRES:
      return isSetUsri4_acct_expires();
    case USRI4_MAX_STORAGE:
      return isSetUsri4_max_storage();
    case USRI4_UNITS_PER_WEEK:
      return isSetUsri4_units_per_week();
    case USRI4_LOGON_HOURS:
      return isSetUsri4_logon_hours();
    case USRI4_BAD_PW_COUNT:
      return isSetUsri4_bad_pw_count();
    case USRI4_NUM_LOGONS:
      return isSetUsri4_num_logons();
    case USRI4_COUNTRY_CODE:
      return isSetUsri4_country_code();
    case USRI4_CODE_PAGE:
      return isSetUsri4_code_page();
    case USRI4_PRIMARY_GROUP_ID:
      return isSetUsri4_primary_group_id();
    case USRI4_PROFILE:
      return isSetUsri4_profile();
    case USRI4_PASSWORD_EXPIRED:
      return isSetUsri4_password_expired();
    case USRI4_AUTH_FLAGS:
      return isSetUsri4_auth_flags();
    case MAC:
      return isSetMac();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof myUserAccountDetailsStruct)
      return this.equals((myUserAccountDetailsStruct)that);
    return false;
  }

  public boolean equals(myUserAccountDetailsStruct that) {
    if (that == null)
      return false;

    boolean this_present_computerName = true && this.isSetComputerName();
    boolean that_present_computerName = true && that.isSetComputerName();
    if (this_present_computerName || that_present_computerName) {
      if (!(this_present_computerName && that_present_computerName))
        return false;
      if (!this.computerName.equals(that.computerName))
        return false;
    }

    boolean this_present_usri4_name = true && this.isSetUsri4_name();
    boolean that_present_usri4_name = true && that.isSetUsri4_name();
    if (this_present_usri4_name || that_present_usri4_name) {
      if (!(this_present_usri4_name && that_present_usri4_name))
        return false;
      if (!this.usri4_name.equals(that.usri4_name))
        return false;
    }

    boolean this_present_usri4_password_age = true && this.isSetUsri4_password_age();
    boolean that_present_usri4_password_age = true && that.isSetUsri4_password_age();
    if (this_present_usri4_password_age || that_present_usri4_password_age) {
      if (!(this_present_usri4_password_age && that_present_usri4_password_age))
        return false;
      if (!this.usri4_password_age.equals(that.usri4_password_age))
        return false;
    }

    boolean this_present_usri4_priv = true && this.isSetUsri4_priv();
    boolean that_present_usri4_priv = true && that.isSetUsri4_priv();
    if (this_present_usri4_priv || that_present_usri4_priv) {
      if (!(this_present_usri4_priv && that_present_usri4_priv))
        return false;
      if (!this.usri4_priv.equals(that.usri4_priv))
        return false;
    }

    boolean this_present_usri4_flags = true && this.isSetUsri4_flags();
    boolean that_present_usri4_flags = true && that.isSetUsri4_flags();
    if (this_present_usri4_flags || that_present_usri4_flags) {
      if (!(this_present_usri4_flags && that_present_usri4_flags))
        return false;
      if (!this.usri4_flags.equals(that.usri4_flags))
        return false;
    }

    boolean this_present_usri4_usr_comment = true && this.isSetUsri4_usr_comment();
    boolean that_present_usri4_usr_comment = true && that.isSetUsri4_usr_comment();
    if (this_present_usri4_usr_comment || that_present_usri4_usr_comment) {
      if (!(this_present_usri4_usr_comment && that_present_usri4_usr_comment))
        return false;
      if (!this.usri4_usr_comment.equals(that.usri4_usr_comment))
        return false;
    }

    boolean this_present_usri4_parms = true && this.isSetUsri4_parms();
    boolean that_present_usri4_parms = true && that.isSetUsri4_parms();
    if (this_present_usri4_parms || that_present_usri4_parms) {
      if (!(this_present_usri4_parms && that_present_usri4_parms))
        return false;
      if (!this.usri4_parms.equals(that.usri4_parms))
        return false;
    }

    boolean this_present_usri4_last_logon = true && this.isSetUsri4_last_logon();
    boolean that_present_usri4_last_logon = true && that.isSetUsri4_last_logon();
    if (this_present_usri4_last_logon || that_present_usri4_last_logon) {
      if (!(this_present_usri4_last_logon && that_present_usri4_last_logon))
        return false;
      if (!this.usri4_last_logon.equals(that.usri4_last_logon))
        return false;
    }

    boolean this_present_usri4_last_logoff = true && this.isSetUsri4_last_logoff();
    boolean that_present_usri4_last_logoff = true && that.isSetUsri4_last_logoff();
    if (this_present_usri4_last_logoff || that_present_usri4_last_logoff) {
      if (!(this_present_usri4_last_logoff && that_present_usri4_last_logoff))
        return false;
      if (!this.usri4_last_logoff.equals(that.usri4_last_logoff))
        return false;
    }

    boolean this_present_usri4_acct_expires = true && this.isSetUsri4_acct_expires();
    boolean that_present_usri4_acct_expires = true && that.isSetUsri4_acct_expires();
    if (this_present_usri4_acct_expires || that_present_usri4_acct_expires) {
      if (!(this_present_usri4_acct_expires && that_present_usri4_acct_expires))
        return false;
      if (!this.usri4_acct_expires.equals(that.usri4_acct_expires))
        return false;
    }

    boolean this_present_usri4_max_storage = true && this.isSetUsri4_max_storage();
    boolean that_present_usri4_max_storage = true && that.isSetUsri4_max_storage();
    if (this_present_usri4_max_storage || that_present_usri4_max_storage) {
      if (!(this_present_usri4_max_storage && that_present_usri4_max_storage))
        return false;
      if (!this.usri4_max_storage.equals(that.usri4_max_storage))
        return false;
    }

    boolean this_present_usri4_units_per_week = true && this.isSetUsri4_units_per_week();
    boolean that_present_usri4_units_per_week = true && that.isSetUsri4_units_per_week();
    if (this_present_usri4_units_per_week || that_present_usri4_units_per_week) {
      if (!(this_present_usri4_units_per_week && that_present_usri4_units_per_week))
        return false;
      if (!this.usri4_units_per_week.equals(that.usri4_units_per_week))
        return false;
    }

    boolean this_present_usri4_logon_hours = true && this.isSetUsri4_logon_hours();
    boolean that_present_usri4_logon_hours = true && that.isSetUsri4_logon_hours();
    if (this_present_usri4_logon_hours || that_present_usri4_logon_hours) {
      if (!(this_present_usri4_logon_hours && that_present_usri4_logon_hours))
        return false;
      if (!this.usri4_logon_hours.equals(that.usri4_logon_hours))
        return false;
    }

    boolean this_present_usri4_bad_pw_count = true && this.isSetUsri4_bad_pw_count();
    boolean that_present_usri4_bad_pw_count = true && that.isSetUsri4_bad_pw_count();
    if (this_present_usri4_bad_pw_count || that_present_usri4_bad_pw_count) {
      if (!(this_present_usri4_bad_pw_count && that_present_usri4_bad_pw_count))
        return false;
      if (!this.usri4_bad_pw_count.equals(that.usri4_bad_pw_count))
        return false;
    }

    boolean this_present_usri4_num_logons = true && this.isSetUsri4_num_logons();
    boolean that_present_usri4_num_logons = true && that.isSetUsri4_num_logons();
    if (this_present_usri4_num_logons || that_present_usri4_num_logons) {
      if (!(this_present_usri4_num_logons && that_present_usri4_num_logons))
        return false;
      if (!this.usri4_num_logons.equals(that.usri4_num_logons))
        return false;
    }

    boolean this_present_usri4_country_code = true && this.isSetUsri4_country_code();
    boolean that_present_usri4_country_code = true && that.isSetUsri4_country_code();
    if (this_present_usri4_country_code || that_present_usri4_country_code) {
      if (!(this_present_usri4_country_code && that_present_usri4_country_code))
        return false;
      if (!this.usri4_country_code.equals(that.usri4_country_code))
        return false;
    }

    boolean this_present_usri4_code_page = true && this.isSetUsri4_code_page();
    boolean that_present_usri4_code_page = true && that.isSetUsri4_code_page();
    if (this_present_usri4_code_page || that_present_usri4_code_page) {
      if (!(this_present_usri4_code_page && that_present_usri4_code_page))
        return false;
      if (!this.usri4_code_page.equals(that.usri4_code_page))
        return false;
    }

    boolean this_present_usri4_primary_group_id = true && this.isSetUsri4_primary_group_id();
    boolean that_present_usri4_primary_group_id = true && that.isSetUsri4_primary_group_id();
    if (this_present_usri4_primary_group_id || that_present_usri4_primary_group_id) {
      if (!(this_present_usri4_primary_group_id && that_present_usri4_primary_group_id))
        return false;
      if (!this.usri4_primary_group_id.equals(that.usri4_primary_group_id))
        return false;
    }

    boolean this_present_usri4_profile = true && this.isSetUsri4_profile();
    boolean that_present_usri4_profile = true && that.isSetUsri4_profile();
    if (this_present_usri4_profile || that_present_usri4_profile) {
      if (!(this_present_usri4_profile && that_present_usri4_profile))
        return false;
      if (!this.usri4_profile.equals(that.usri4_profile))
        return false;
    }

    boolean this_present_usri4_password_expired = true && this.isSetUsri4_password_expired();
    boolean that_present_usri4_password_expired = true && that.isSetUsri4_password_expired();
    if (this_present_usri4_password_expired || that_present_usri4_password_expired) {
      if (!(this_present_usri4_password_expired && that_present_usri4_password_expired))
        return false;
      if (!this.usri4_password_expired.equals(that.usri4_password_expired))
        return false;
    }

    boolean this_present_usri4_auth_flags = true && this.isSetUsri4_auth_flags();
    boolean that_present_usri4_auth_flags = true && that.isSetUsri4_auth_flags();
    if (this_present_usri4_auth_flags || that_present_usri4_auth_flags) {
      if (!(this_present_usri4_auth_flags && that_present_usri4_auth_flags))
        return false;
      if (!this.usri4_auth_flags.equals(that.usri4_auth_flags))
        return false;
    }

    boolean this_present_mac = true && this.isSetMac();
    boolean that_present_mac = true && that.isSetMac();
    if (this_present_mac || that_present_mac) {
      if (!(this_present_mac && that_present_mac))
        return false;
      if (!this.mac.equals(that.mac))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_computerName = true && (isSetComputerName());
    list.add(present_computerName);
    if (present_computerName)
      list.add(computerName);

    boolean present_usri4_name = true && (isSetUsri4_name());
    list.add(present_usri4_name);
    if (present_usri4_name)
      list.add(usri4_name);

    boolean present_usri4_password_age = true && (isSetUsri4_password_age());
    list.add(present_usri4_password_age);
    if (present_usri4_password_age)
      list.add(usri4_password_age);

    boolean present_usri4_priv = true && (isSetUsri4_priv());
    list.add(present_usri4_priv);
    if (present_usri4_priv)
      list.add(usri4_priv);

    boolean present_usri4_flags = true && (isSetUsri4_flags());
    list.add(present_usri4_flags);
    if (present_usri4_flags)
      list.add(usri4_flags);

    boolean present_usri4_usr_comment = true && (isSetUsri4_usr_comment());
    list.add(present_usri4_usr_comment);
    if (present_usri4_usr_comment)
      list.add(usri4_usr_comment);

    boolean present_usri4_parms = true && (isSetUsri4_parms());
    list.add(present_usri4_parms);
    if (present_usri4_parms)
      list.add(usri4_parms);

    boolean present_usri4_last_logon = true && (isSetUsri4_last_logon());
    list.add(present_usri4_last_logon);
    if (present_usri4_last_logon)
      list.add(usri4_last_logon);

    boolean present_usri4_last_logoff = true && (isSetUsri4_last_logoff());
    list.add(present_usri4_last_logoff);
    if (present_usri4_last_logoff)
      list.add(usri4_last_logoff);

    boolean present_usri4_acct_expires = true && (isSetUsri4_acct_expires());
    list.add(present_usri4_acct_expires);
    if (present_usri4_acct_expires)
      list.add(usri4_acct_expires);

    boolean present_usri4_max_storage = true && (isSetUsri4_max_storage());
    list.add(present_usri4_max_storage);
    if (present_usri4_max_storage)
      list.add(usri4_max_storage);

    boolean present_usri4_units_per_week = true && (isSetUsri4_units_per_week());
    list.add(present_usri4_units_per_week);
    if (present_usri4_units_per_week)
      list.add(usri4_units_per_week);

    boolean present_usri4_logon_hours = true && (isSetUsri4_logon_hours());
    list.add(present_usri4_logon_hours);
    if (present_usri4_logon_hours)
      list.add(usri4_logon_hours);

    boolean present_usri4_bad_pw_count = true && (isSetUsri4_bad_pw_count());
    list.add(present_usri4_bad_pw_count);
    if (present_usri4_bad_pw_count)
      list.add(usri4_bad_pw_count);

    boolean present_usri4_num_logons = true && (isSetUsri4_num_logons());
    list.add(present_usri4_num_logons);
    if (present_usri4_num_logons)
      list.add(usri4_num_logons);

    boolean present_usri4_country_code = true && (isSetUsri4_country_code());
    list.add(present_usri4_country_code);
    if (present_usri4_country_code)
      list.add(usri4_country_code);

    boolean present_usri4_code_page = true && (isSetUsri4_code_page());
    list.add(present_usri4_code_page);
    if (present_usri4_code_page)
      list.add(usri4_code_page);

    boolean present_usri4_primary_group_id = true && (isSetUsri4_primary_group_id());
    list.add(present_usri4_primary_group_id);
    if (present_usri4_primary_group_id)
      list.add(usri4_primary_group_id);

    boolean present_usri4_profile = true && (isSetUsri4_profile());
    list.add(present_usri4_profile);
    if (present_usri4_profile)
      list.add(usri4_profile);

    boolean present_usri4_password_expired = true && (isSetUsri4_password_expired());
    list.add(present_usri4_password_expired);
    if (present_usri4_password_expired)
      list.add(usri4_password_expired);

    boolean present_usri4_auth_flags = true && (isSetUsri4_auth_flags());
    list.add(present_usri4_auth_flags);
    if (present_usri4_auth_flags)
      list.add(usri4_auth_flags);

    boolean present_mac = true && (isSetMac());
    list.add(present_mac);
    if (present_mac)
      list.add(mac);

    return list.hashCode();
  }

  @Override
  public int compareTo(myUserAccountDetailsStruct other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetComputerName()).compareTo(other.isSetComputerName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetComputerName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.computerName, other.computerName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_name()).compareTo(other.isSetUsri4_name());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_name()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_name, other.usri4_name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_password_age()).compareTo(other.isSetUsri4_password_age());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_password_age()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_password_age, other.usri4_password_age);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_priv()).compareTo(other.isSetUsri4_priv());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_priv()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_priv, other.usri4_priv);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_flags()).compareTo(other.isSetUsri4_flags());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_flags()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_flags, other.usri4_flags);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_usr_comment()).compareTo(other.isSetUsri4_usr_comment());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_usr_comment()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_usr_comment, other.usri4_usr_comment);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_parms()).compareTo(other.isSetUsri4_parms());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_parms()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_parms, other.usri4_parms);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_last_logon()).compareTo(other.isSetUsri4_last_logon());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_last_logon()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_last_logon, other.usri4_last_logon);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_last_logoff()).compareTo(other.isSetUsri4_last_logoff());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_last_logoff()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_last_logoff, other.usri4_last_logoff);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_acct_expires()).compareTo(other.isSetUsri4_acct_expires());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_acct_expires()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_acct_expires, other.usri4_acct_expires);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_max_storage()).compareTo(other.isSetUsri4_max_storage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_max_storage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_max_storage, other.usri4_max_storage);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_units_per_week()).compareTo(other.isSetUsri4_units_per_week());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_units_per_week()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_units_per_week, other.usri4_units_per_week);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_logon_hours()).compareTo(other.isSetUsri4_logon_hours());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_logon_hours()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_logon_hours, other.usri4_logon_hours);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_bad_pw_count()).compareTo(other.isSetUsri4_bad_pw_count());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_bad_pw_count()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_bad_pw_count, other.usri4_bad_pw_count);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_num_logons()).compareTo(other.isSetUsri4_num_logons());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_num_logons()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_num_logons, other.usri4_num_logons);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_country_code()).compareTo(other.isSetUsri4_country_code());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_country_code()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_country_code, other.usri4_country_code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_code_page()).compareTo(other.isSetUsri4_code_page());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_code_page()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_code_page, other.usri4_code_page);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_primary_group_id()).compareTo(other.isSetUsri4_primary_group_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_primary_group_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_primary_group_id, other.usri4_primary_group_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_profile()).compareTo(other.isSetUsri4_profile());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_profile()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_profile, other.usri4_profile);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_password_expired()).compareTo(other.isSetUsri4_password_expired());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_password_expired()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_password_expired, other.usri4_password_expired);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUsri4_auth_flags()).compareTo(other.isSetUsri4_auth_flags());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsri4_auth_flags()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usri4_auth_flags, other.usri4_auth_flags);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMac()).compareTo(other.isSetMac());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMac()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.mac, other.mac);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("myUserAccountDetailsStruct(");
    boolean first = true;

    sb.append("computerName:");
    if (this.computerName == null) {
      sb.append("null");
    } else {
      sb.append(this.computerName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_name:");
    if (this.usri4_name == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_password_age:");
    if (this.usri4_password_age == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_password_age);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_priv:");
    if (this.usri4_priv == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_priv);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_flags:");
    if (this.usri4_flags == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_flags);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_usr_comment:");
    if (this.usri4_usr_comment == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_usr_comment);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_parms:");
    if (this.usri4_parms == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_parms);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_last_logon:");
    if (this.usri4_last_logon == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_last_logon);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_last_logoff:");
    if (this.usri4_last_logoff == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_last_logoff);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_acct_expires:");
    if (this.usri4_acct_expires == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_acct_expires);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_max_storage:");
    if (this.usri4_max_storage == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_max_storage);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_units_per_week:");
    if (this.usri4_units_per_week == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_units_per_week);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_logon_hours:");
    if (this.usri4_logon_hours == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_logon_hours);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_bad_pw_count:");
    if (this.usri4_bad_pw_count == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_bad_pw_count);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_num_logons:");
    if (this.usri4_num_logons == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_num_logons);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_country_code:");
    if (this.usri4_country_code == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_country_code);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_code_page:");
    if (this.usri4_code_page == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_code_page);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_primary_group_id:");
    if (this.usri4_primary_group_id == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_primary_group_id);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_profile:");
    if (this.usri4_profile == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_profile);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_password_expired:");
    if (this.usri4_password_expired == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_password_expired);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("usri4_auth_flags:");
    if (this.usri4_auth_flags == null) {
      sb.append("null");
    } else {
      sb.append(this.usri4_auth_flags);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("mac:");
    if (this.mac == null) {
      sb.append("null");
    } else {
      sb.append(this.mac);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class myUserAccountDetailsStructStandardSchemeFactory implements SchemeFactory {
    public myUserAccountDetailsStructStandardScheme getScheme() {
      return new myUserAccountDetailsStructStandardScheme();
    }
  }

  private static class myUserAccountDetailsStructStandardScheme extends StandardScheme<myUserAccountDetailsStruct> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, myUserAccountDetailsStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // COMPUTER_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.computerName = iprot.readString();
              struct.setComputerNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // USRI4_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_name = iprot.readString();
              struct.setUsri4_nameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // USRI4_PASSWORD_AGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_password_age = iprot.readString();
              struct.setUsri4_password_ageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // USRI4_PRIV
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_priv = iprot.readString();
              struct.setUsri4_privIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // USRI4_FLAGS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_flags = iprot.readString();
              struct.setUsri4_flagsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // USRI4_USR_COMMENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_usr_comment = iprot.readString();
              struct.setUsri4_usr_commentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // USRI4_PARMS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_parms = iprot.readString();
              struct.setUsri4_parmsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // USRI4_LAST_LOGON
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_last_logon = iprot.readString();
              struct.setUsri4_last_logonIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // USRI4_LAST_LOGOFF
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_last_logoff = iprot.readString();
              struct.setUsri4_last_logoffIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // USRI4_ACCT_EXPIRES
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_acct_expires = iprot.readString();
              struct.setUsri4_acct_expiresIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // USRI4_MAX_STORAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_max_storage = iprot.readString();
              struct.setUsri4_max_storageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // USRI4_UNITS_PER_WEEK
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_units_per_week = iprot.readString();
              struct.setUsri4_units_per_weekIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // USRI4_LOGON_HOURS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_logon_hours = iprot.readString();
              struct.setUsri4_logon_hoursIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // USRI4_BAD_PW_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_bad_pw_count = iprot.readString();
              struct.setUsri4_bad_pw_countIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 15: // USRI4_NUM_LOGONS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_num_logons = iprot.readString();
              struct.setUsri4_num_logonsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 16: // USRI4_COUNTRY_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_country_code = iprot.readString();
              struct.setUsri4_country_codeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 17: // USRI4_CODE_PAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_code_page = iprot.readString();
              struct.setUsri4_code_pageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 18: // USRI4_PRIMARY_GROUP_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_primary_group_id = iprot.readString();
              struct.setUsri4_primary_group_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 19: // USRI4_PROFILE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_profile = iprot.readString();
              struct.setUsri4_profileIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 20: // USRI4_PASSWORD_EXPIRED
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_password_expired = iprot.readString();
              struct.setUsri4_password_expiredIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 21: // USRI4_AUTH_FLAGS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.usri4_auth_flags = iprot.readString();
              struct.setUsri4_auth_flagsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 22: // MAC
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.mac = iprot.readString();
              struct.setMacIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, myUserAccountDetailsStruct struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.computerName != null) {
        oprot.writeFieldBegin(COMPUTER_NAME_FIELD_DESC);
        oprot.writeString(struct.computerName);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_name != null) {
        oprot.writeFieldBegin(USRI4_NAME_FIELD_DESC);
        oprot.writeString(struct.usri4_name);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_password_age != null) {
        oprot.writeFieldBegin(USRI4_PASSWORD_AGE_FIELD_DESC);
        oprot.writeString(struct.usri4_password_age);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_priv != null) {
        oprot.writeFieldBegin(USRI4_PRIV_FIELD_DESC);
        oprot.writeString(struct.usri4_priv);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_flags != null) {
        oprot.writeFieldBegin(USRI4_FLAGS_FIELD_DESC);
        oprot.writeString(struct.usri4_flags);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_usr_comment != null) {
        oprot.writeFieldBegin(USRI4_USR_COMMENT_FIELD_DESC);
        oprot.writeString(struct.usri4_usr_comment);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_parms != null) {
        oprot.writeFieldBegin(USRI4_PARMS_FIELD_DESC);
        oprot.writeString(struct.usri4_parms);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_last_logon != null) {
        oprot.writeFieldBegin(USRI4_LAST_LOGON_FIELD_DESC);
        oprot.writeString(struct.usri4_last_logon);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_last_logoff != null) {
        oprot.writeFieldBegin(USRI4_LAST_LOGOFF_FIELD_DESC);
        oprot.writeString(struct.usri4_last_logoff);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_acct_expires != null) {
        oprot.writeFieldBegin(USRI4_ACCT_EXPIRES_FIELD_DESC);
        oprot.writeString(struct.usri4_acct_expires);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_max_storage != null) {
        oprot.writeFieldBegin(USRI4_MAX_STORAGE_FIELD_DESC);
        oprot.writeString(struct.usri4_max_storage);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_units_per_week != null) {
        oprot.writeFieldBegin(USRI4_UNITS_PER_WEEK_FIELD_DESC);
        oprot.writeString(struct.usri4_units_per_week);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_logon_hours != null) {
        oprot.writeFieldBegin(USRI4_LOGON_HOURS_FIELD_DESC);
        oprot.writeString(struct.usri4_logon_hours);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_bad_pw_count != null) {
        oprot.writeFieldBegin(USRI4_BAD_PW_COUNT_FIELD_DESC);
        oprot.writeString(struct.usri4_bad_pw_count);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_num_logons != null) {
        oprot.writeFieldBegin(USRI4_NUM_LOGONS_FIELD_DESC);
        oprot.writeString(struct.usri4_num_logons);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_country_code != null) {
        oprot.writeFieldBegin(USRI4_COUNTRY_CODE_FIELD_DESC);
        oprot.writeString(struct.usri4_country_code);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_code_page != null) {
        oprot.writeFieldBegin(USRI4_CODE_PAGE_FIELD_DESC);
        oprot.writeString(struct.usri4_code_page);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_primary_group_id != null) {
        oprot.writeFieldBegin(USRI4_PRIMARY_GROUP_ID_FIELD_DESC);
        oprot.writeString(struct.usri4_primary_group_id);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_profile != null) {
        oprot.writeFieldBegin(USRI4_PROFILE_FIELD_DESC);
        oprot.writeString(struct.usri4_profile);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_password_expired != null) {
        oprot.writeFieldBegin(USRI4_PASSWORD_EXPIRED_FIELD_DESC);
        oprot.writeString(struct.usri4_password_expired);
        oprot.writeFieldEnd();
      }
      if (struct.usri4_auth_flags != null) {
        oprot.writeFieldBegin(USRI4_AUTH_FLAGS_FIELD_DESC);
        oprot.writeString(struct.usri4_auth_flags);
        oprot.writeFieldEnd();
      }
      if (struct.mac != null) {
        oprot.writeFieldBegin(MAC_FIELD_DESC);
        oprot.writeString(struct.mac);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class myUserAccountDetailsStructTupleSchemeFactory implements SchemeFactory {
    public myUserAccountDetailsStructTupleScheme getScheme() {
      return new myUserAccountDetailsStructTupleScheme();
    }
  }

  private static class myUserAccountDetailsStructTupleScheme extends TupleScheme<myUserAccountDetailsStruct> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, myUserAccountDetailsStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetComputerName()) {
        optionals.set(0);
      }
      if (struct.isSetUsri4_name()) {
        optionals.set(1);
      }
      if (struct.isSetUsri4_password_age()) {
        optionals.set(2);
      }
      if (struct.isSetUsri4_priv()) {
        optionals.set(3);
      }
      if (struct.isSetUsri4_flags()) {
        optionals.set(4);
      }
      if (struct.isSetUsri4_usr_comment()) {
        optionals.set(5);
      }
      if (struct.isSetUsri4_parms()) {
        optionals.set(6);
      }
      if (struct.isSetUsri4_last_logon()) {
        optionals.set(7);
      }
      if (struct.isSetUsri4_last_logoff()) {
        optionals.set(8);
      }
      if (struct.isSetUsri4_acct_expires()) {
        optionals.set(9);
      }
      if (struct.isSetUsri4_max_storage()) {
        optionals.set(10);
      }
      if (struct.isSetUsri4_units_per_week()) {
        optionals.set(11);
      }
      if (struct.isSetUsri4_logon_hours()) {
        optionals.set(12);
      }
      if (struct.isSetUsri4_bad_pw_count()) {
        optionals.set(13);
      }
      if (struct.isSetUsri4_num_logons()) {
        optionals.set(14);
      }
      if (struct.isSetUsri4_country_code()) {
        optionals.set(15);
      }
      if (struct.isSetUsri4_code_page()) {
        optionals.set(16);
      }
      if (struct.isSetUsri4_primary_group_id()) {
        optionals.set(17);
      }
      if (struct.isSetUsri4_profile()) {
        optionals.set(18);
      }
      if (struct.isSetUsri4_password_expired()) {
        optionals.set(19);
      }
      if (struct.isSetUsri4_auth_flags()) {
        optionals.set(20);
      }
      if (struct.isSetMac()) {
        optionals.set(21);
      }
      oprot.writeBitSet(optionals, 22);
      if (struct.isSetComputerName()) {
        oprot.writeString(struct.computerName);
      }
      if (struct.isSetUsri4_name()) {
        oprot.writeString(struct.usri4_name);
      }
      if (struct.isSetUsri4_password_age()) {
        oprot.writeString(struct.usri4_password_age);
      }
      if (struct.isSetUsri4_priv()) {
        oprot.writeString(struct.usri4_priv);
      }
      if (struct.isSetUsri4_flags()) {
        oprot.writeString(struct.usri4_flags);
      }
      if (struct.isSetUsri4_usr_comment()) {
        oprot.writeString(struct.usri4_usr_comment);
      }
      if (struct.isSetUsri4_parms()) {
        oprot.writeString(struct.usri4_parms);
      }
      if (struct.isSetUsri4_last_logon()) {
        oprot.writeString(struct.usri4_last_logon);
      }
      if (struct.isSetUsri4_last_logoff()) {
        oprot.writeString(struct.usri4_last_logoff);
      }
      if (struct.isSetUsri4_acct_expires()) {
        oprot.writeString(struct.usri4_acct_expires);
      }
      if (struct.isSetUsri4_max_storage()) {
        oprot.writeString(struct.usri4_max_storage);
      }
      if (struct.isSetUsri4_units_per_week()) {
        oprot.writeString(struct.usri4_units_per_week);
      }
      if (struct.isSetUsri4_logon_hours()) {
        oprot.writeString(struct.usri4_logon_hours);
      }
      if (struct.isSetUsri4_bad_pw_count()) {
        oprot.writeString(struct.usri4_bad_pw_count);
      }
      if (struct.isSetUsri4_num_logons()) {
        oprot.writeString(struct.usri4_num_logons);
      }
      if (struct.isSetUsri4_country_code()) {
        oprot.writeString(struct.usri4_country_code);
      }
      if (struct.isSetUsri4_code_page()) {
        oprot.writeString(struct.usri4_code_page);
      }
      if (struct.isSetUsri4_primary_group_id()) {
        oprot.writeString(struct.usri4_primary_group_id);
      }
      if (struct.isSetUsri4_profile()) {
        oprot.writeString(struct.usri4_profile);
      }
      if (struct.isSetUsri4_password_expired()) {
        oprot.writeString(struct.usri4_password_expired);
      }
      if (struct.isSetUsri4_auth_flags()) {
        oprot.writeString(struct.usri4_auth_flags);
      }
      if (struct.isSetMac()) {
        oprot.writeString(struct.mac);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, myUserAccountDetailsStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(22);
      if (incoming.get(0)) {
        struct.computerName = iprot.readString();
        struct.setComputerNameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.usri4_name = iprot.readString();
        struct.setUsri4_nameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.usri4_password_age = iprot.readString();
        struct.setUsri4_password_ageIsSet(true);
      }
      if (incoming.get(3)) {
        struct.usri4_priv = iprot.readString();
        struct.setUsri4_privIsSet(true);
      }
      if (incoming.get(4)) {
        struct.usri4_flags = iprot.readString();
        struct.setUsri4_flagsIsSet(true);
      }
      if (incoming.get(5)) {
        struct.usri4_usr_comment = iprot.readString();
        struct.setUsri4_usr_commentIsSet(true);
      }
      if (incoming.get(6)) {
        struct.usri4_parms = iprot.readString();
        struct.setUsri4_parmsIsSet(true);
      }
      if (incoming.get(7)) {
        struct.usri4_last_logon = iprot.readString();
        struct.setUsri4_last_logonIsSet(true);
      }
      if (incoming.get(8)) {
        struct.usri4_last_logoff = iprot.readString();
        struct.setUsri4_last_logoffIsSet(true);
      }
      if (incoming.get(9)) {
        struct.usri4_acct_expires = iprot.readString();
        struct.setUsri4_acct_expiresIsSet(true);
      }
      if (incoming.get(10)) {
        struct.usri4_max_storage = iprot.readString();
        struct.setUsri4_max_storageIsSet(true);
      }
      if (incoming.get(11)) {
        struct.usri4_units_per_week = iprot.readString();
        struct.setUsri4_units_per_weekIsSet(true);
      }
      if (incoming.get(12)) {
        struct.usri4_logon_hours = iprot.readString();
        struct.setUsri4_logon_hoursIsSet(true);
      }
      if (incoming.get(13)) {
        struct.usri4_bad_pw_count = iprot.readString();
        struct.setUsri4_bad_pw_countIsSet(true);
      }
      if (incoming.get(14)) {
        struct.usri4_num_logons = iprot.readString();
        struct.setUsri4_num_logonsIsSet(true);
      }
      if (incoming.get(15)) {
        struct.usri4_country_code = iprot.readString();
        struct.setUsri4_country_codeIsSet(true);
      }
      if (incoming.get(16)) {
        struct.usri4_code_page = iprot.readString();
        struct.setUsri4_code_pageIsSet(true);
      }
      if (incoming.get(17)) {
        struct.usri4_primary_group_id = iprot.readString();
        struct.setUsri4_primary_group_idIsSet(true);
      }
      if (incoming.get(18)) {
        struct.usri4_profile = iprot.readString();
        struct.setUsri4_profileIsSet(true);
      }
      if (incoming.get(19)) {
        struct.usri4_password_expired = iprot.readString();
        struct.setUsri4_password_expiredIsSet(true);
      }
      if (incoming.get(20)) {
        struct.usri4_auth_flags = iprot.readString();
        struct.setUsri4_auth_flagsIsSet(true);
      }
      if (incoming.get(21)) {
        struct.mac = iprot.readString();
        struct.setMacIsSet(true);
      }
    }
  }

}

